[package]
name = "adamant"
version = "0.1.0"
authors = ["Matteo Meli <matteo.meli@gmail.com>"]
edition = "2018"

[lib]
name = "adamant"
path = "src/lib.rs"

[[bin]]
name = "adamant"
path = "src/main.rs"
